### ISSUE TITLE
Index.html should add parsed script as JS

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#1]
Warning message from Firefox >>> `The script from “https://berinhard.github.io/sketches/s_179/__target__/s_179.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.[Learn More] s_179`

The issue is with the `type="module"` in the script's js tag.
​

**Comment by villares** [comment]
While you are working on the `index.html` generation:

`The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.`

**Comment by berinhard** [comment]
Thanks @villares! I guess this have to do with the current raw version of `index.html`. It doesn't have the higher level tags such as `<html>`, the one which I should place the encoding. :+1:

**Comment by berinhard** [comment]
The problem lives in the name of the directory we're saving our JS files. For some reason, assets with `__` in the filename are not working well with github.io. So, we have to rename the dir from `__target__` to `target`. Use [this commit](https://github.com/berinhard/sketches/commit/4545779b9ed0d013222762a0aff86443b3b75874) as reference.
