### ISSUE TITLE
Serve ACE editor files from Flask app

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#107]
Currently we're [relying on cdnjs](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/http/templates/view_sketch.html#L51) to serve the ACE editor JS files. Although this was a quick fix to add the editor, it's not ideal since it prevents people from using `pyp5js` offline.

So we have to serve IDE from the flask application as well to avoid this dependency.

**Comment by berinhard** [comment]
The same this is valid for the p5.js file

**Comment by pedroqueiroga** [comment]
We could copy the pre-built version into the static js directory, kind of like [ace.js](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/http/static/js/ace.js) currently present but missing its dependencies. Alternatively, and I think this way would be better to keep up with changes, we could integrate npm in the current environment and use `make` calling `python setup.py` and `npm install`?

**Comment by pedroqueiroga** [comment]
> The same is valid for the p5.js file

I checked around and couldn't find a reference for p5.js as an external resource. Is this already solved?
