### ISSUE TITLE
p5.Vector methods not working in pyodide

### ISSUE THREAD

**Issue by jvfe** [berinhard/pyp5js#135]
I've adapted the [p5js random2D example](https://p5js.org/reference/#/p5.Vector/random2D) to pyp5js:

```py
from pyp5js import *

def drawArrow(base, vec, myColor):
    
  push()
  
  stroke(myColor)
  strokeWeight(3)
  fill(myColor)
  
  translate(base.x, base.y)
  line(0, 0, vec.x, vec.y)
  rotate(vec.heading())
  
  arrowSize = 7
  translate(vec.mag() - arrowSize, 0)
  triangle(0, arrowSize / 2, 0, -arrowSize / 2, arrowSize, 0)
  
  pop()


def setup():
    
  frameRate(1)


def draw():
  background(240)

  v0 = createVector(50, 50)
  v1 = p5.Vector.random2D()
  drawArrow(v0, v1.mult(50), 'black')
```

And, while it runs fine locally, using transcrypt, it doesn't work in [the pyodide demo](https://berinhard.github.io/pyp5js/pyodide/). The error raised in the console is an AttributeError, `'JsBoundMethod' object has no attribute 'random2D'`. I've noticed the same is true for other p5.Vector methods, such as lerp(). 

Might be related to issues while trying to implement #125.

**Comment by villares** [comment]
The recent `PVector` wrapper addition, merged today, can access these methods, but it essential to be able to access the `p5js.org` way!

**Comment by berinhard** [comment]
Thanks @jvfe for documenting this. I tested this code both locally and in the demo editor and it worked in both envs. So, I'm closing this issue.
