### ISSUE TITLE
Enable the mouseWheel() event function feature

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#161]
We need accesss to the  `.delta` attribute from the `p5js` event, inside `mouseWheel()`....

![image](https://user-images.githubusercontent.com/3694604/115118832-94224600-9f7b-11eb-8bc4-406d8d6b5050.png)

But it would be nice to add a `.getCount()` method to the event, if possible, for Java/Python mode compatibility...

![image](https://user-images.githubusercontent.com/3694604/115118801-676e2e80-9f7b-11eb-9c67-7fe2950d5bea.png)

**Comment by berinhard** [comment]
This should be added to both pyodide and transcrypt modes

**Comment by berinhard** [comment]
@villares as in #164, the issue only happens with the demo editor mode. Here's a screen shot:

![Screenshot from 2021-10-16 11-23-38](https://user-images.githubusercontent.com/238223/137591338-8235d8db-2c0b-4567-9a6b-a2154095ef96.png)

Although we know it is a problem, I'm also de-prioritizing this issue by now to focus on Pyodide's support and integrations. I'm also removing this issue from [Pyodide's fine tunning milestone](https://github.com/berinhard/pyp5js/milestone/4). To better document issues related with the demo editor, I've created the [Demo Editor](https://github.com/berinhard/pyp5js/labels/Demo%20Editor) label. Feel free to use them when you notice it's an issue exclusive from the demo editor.
