### ISSUE TITLE
Event functions seem to be running more times than expected

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#164]
Minimal code to test issue:
```python
def setup():
    createCanvas(200, 200)
    background(160)

def draw():
    fill("blue")
    # background(200)
    d = sin(frameCount / 60) * 50 + 50
    ellipse(100, 100, d, d)

def keyReleased():
    print(key)
    background(0)
```
Expected behaviour, `keyReleased()` should run only once when a key is released. In the screenshot below I saw it run three times.
Maybe related: Could it be that several `pyodide` instances are running simultaneously? I have tried this imeadiatly after refreshing the page, so it seems unlikely.
![image](https://user-images.githubusercontent.com/3694604/115151096-cac29400-a041-11eb-93ec-2e090c0e682d.png)

**Comment by berinhard** [comment]
Hm, not sure if there's a change of having multiple pyodide instances because pyp5js uses a single entry point to load it after the page loads. Will investigate this.

**Comment by villares** [comment]
Hi, sorry to report something has changed and the demo pyodide seems not to be responding to any event functions anymore :(
I have tested https://berinhard.github.io/pyp5js/pyodide/ with the same test code as above in this issue. 

![image](https://user-images.githubusercontent.com/3694604/129285928-4a5623a2-2542-4c5c-a21c-35d6b2dba3a5.png)

**Comment by berinhard** [comment]
Even after merging #185 and updating the demo to use the most up to date version of pyodide's integration, the events are still being triggered multiple times **only in the demo editor**.

**Comment by jvfe** [comment]
> @jvfe maybe I'm asking too much, but it you want to help with that, it would be awesome =)

I'm taking a look at it but I don't see what might be the reason for these events getting called twice every time. I'll keep you updated if I find anything.
