### ISSUE TITLE
Online demo editor stopped working?

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#180]
https://berinhard.github.io/pyp5js/pyodide/

![image](https://user-images.githubusercontent.com/3694604/135723081-ddb2786a-f423-4fc8-b40d-51a4539eeab9.png)

My clumsy old & hacked fork at https://abav.lugaralgum.com/pyp5js/pyodide/
still works.

**Comment by berinhard** [comment]
Thanks for the catch @villares! I worked on the docs updates recently and had to change the github pages to build from the `dev` branch instead of the `main` one. I rolled back and now it's working.

Anyway, I'll leave this issue open since I still have to fix this on the `dev` branch.
