### ISSUE TITLE
Python implementation for `keyPressed` or `mousePressed` are not being linked to P5.js

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#19]
The keyboard or mouse events are not being processd by the python functions. I discovered that while transcribing the examples from @esperanc [Brython Ide examples](https://github.com/esperanc/brythonide/tree/master/demoSketches). 

Probably we'll have to create new functions `keyPressed` and `mouseEvent` in pytop5js.py with indirect calls to the Python implementation. @villares are there other methods to deal with events besides those two?

**Comment by berinhard** [comment]
Same for:

- `mouseDragged`
- `mouseReleased`

**Comment by villares** [comment]
keyReleased()
mouseClicked()
mouseMoved()
mouseWheel(event)

There are also some "touch" events documented on the p5js reference for
mobile devices.

**Comment by berinhard** [comment]
I did some upgrade on this issue and my WIP is under [the branch `feature/event-functions`](https://github.com/berinhard/pyp5js/tree/feature/event-functions). The main approach and strategy is defined in beb21bb5e81d2a406ec3f5eba70aa72a88620046, but I'm definitely not happy with the current implementation.

I've uploaded [an example](https://berinhard.github.io/sketches/#s_187) using this initial approach working on my sketches' repository.

**Comment by berinhard** [comment]
@villares I think I'll implement an intermediary solution for this issue. What I'm thinking to do is to enable to use the events methods by defining config dictionary and passing it to `start_p5`. The final sketch would look like this:

```python
from pytop5js import *

def setup():
    createCanvas(200, 200)
    background(160)


def draw():
    fill('blue')
    background(200)
    r = sin(frameCount / 60) * 50 + 50
    ellipse(100, 100, r, r)

def keyPressed():
    #### some logic here
    pass

def mouseMoved():
    #### mouse logic here
    pass

event_methods = {
    "keyPressed": keyPressed,
    "mouseMoved" mouseMoved
}
start_p5(setup, draw, event_methods)
```

As I said, this is the first step. My main goal is to consolidate `start_p5` internal API. Once it's working and supporting all the events, I think the next move would be to remove the requirement from the `sketch.py` to call `start_p5` correctly. I **really** think we'll end up on creating a new `temp_sketch.py` to be compiled by transcrypt. This `temp_sketch.py` would be similar to something like this:

```python
from sketch import setup, draw
try:
    from sketch import keyPressed
except ImportError
    keyPressed = None
#### same try import/except None structure for the other event methods

event_methods = {}

if keyPressed:
    event_methods["keyPressed"] = keyPressed
if mouseMoved:
    event_methods["mouseMoved"] = mouseMoved
### this goes on for all event methods

start_p5(setup, draw, even_methods)
```

**Comment by villares** [comment]
Yep! Looks good!

I'm very conflicted about having both the first `from pytop5js import *` and the ending `start_p5(setup, draw, even_methods)` when this is all over. As a teacher, the `start_p5()` is pedagogical... but it could easily be removed.

I would make the `temp_sketch.py` be named `target_sketch.py`, perhaps inside the *target* folder. Have you noticed Transcrypt is creating a duplicate there?

**Comment by villares** [comment]
Hi @berinhard there are more events we might need to consider, like: [`windowResized()`](https://p5js.org/reference/#/p5/windowResized)

**Comment by eduardostalinho** [comment]
I think the solution can fit more.
Maybe if we make some refactoring extracting only things about events in a different module we will se the behaviour of the code emerging.

One thing that is happening is that when I develop a sketch with only `draw` and `setup`, I have to pass one dict argument that does not make sense for me, just because of events.
https://github.com/berinhard/pyp5js/blob/41c5c75c740d1461f6a5961c1d40fbd37baf4ef5/docs/examples/sketch_001/sketch_001.py#L36
I think this is leaking implementation.

A hypothesys that appear to me is receiving a `*event_methods` in `start_p5` and the user will pass the event methods as she wants. But it's only a hypothesys that can be validated with more assertiveness while we refactor the events internal implementation.

PS.: I don't know if this refactoring is simple using transcrypt.
