### ISSUE TITLE
Update demo editor "Run" button to be deactivated until Pyodide finishes loading

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#197]
Currently, if the users click on the "Run" button before the demo sketch appears, they get the following error:

```
Uncaught TypeError: window.runSketchCode is not a function
    runCode https://berinhard.github.io/pyp5js/pyodide/:104
    <anonymous> https://berinhard.github.io/pyp5js/pyodide/:124
    jQuery 2
```

But when the sketch starts to run, the run button gets back to work properly. It's probable that issue #189 will make it easier to implement this feature.

**Comment by jvfe** [comment]
A simple, but not ideal fix, would be to change [these lines](https://github.com/berinhard/pyp5js/blob/5ad4750a15b0101f49c8466ecd4cba753c6c672b/docs/pyodide/index.html#L123-L124) to be:
```js
$("#executeBtn").on("click", () => { (window.instance) ? runCode() : null; });
$("#clearBtn").on("click", () => { (window.instance) ? window.instance.remove() : null; });
```
Then the click event would only be fired once p5's window.instance object is created.

**Comment by berinhard** [comment]
@jvfe I think what you're suggesting is very reasonable. Maybe we can add an `else` condition to the `executeBtn` logic to display an alert box with a message like: "Pyodide is still loading. Please, wait a few seconds and try to run it again."
