### ISSUE TITLE
P5.Vector does not have Python Mode's operator overloading sugar

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#20]
Should we re-implement Processing Python Mode's PVector (now in pure Python)?
Could we just add the dunder methods (like `__add__()` ) hooks on transcrypt?
[And I confess that I find createVector() ugly/strange]

**Comment by villares** [comment]
This comment is to document that operator overloading needs special "pragma" to work on Transcrypt :(

**Comment by berinhard** [comment]
Hm, not necessarily. We can rely on turning on/off the operator overloading with __pragma__ as explained [in the docs](https://transcrypt.org/docs/html/special_facilities.html#operator-overloading-pragma-opov-and-pragma-noopov) or we can also change how we run the transcrypt command to add the `--opov` flag. By the flag descriptions, it can bring performance issues:

```
  -o, --opov            enable operator overloading by default. In general
                        this is disadvised, use __pragma__ ('opov') and
                        __pragma__('noopov') locally instead to prevent slow
                        code
```

**Comment by villares** [comment]
I know this is of no importance/priority at all, jut to record a silly crazy naïve idea for adding experimental somewhat-"local" operator overloading on Transcrypt (could be activated with a -experimentalopov flag).
- Read all code looking for names in lines with the PVector name.
- Read again looking for names in lines containing those names.
- Envelop code blocks containing the found names or the PVector name with `__pragma__ ('opov')` and ` __pragma__('noopov')` .
Now let's go back to important work...

**Comment by berinhard** [comment]
I'm closing this issue because now pyp5js support operator overloading under pyodide (default) mode. I'm labeling this issue as "Transcrypt Requirement" and closing it.
