### ISSUE TITLE
can't run https://berinhard.github.io/pyp5js/pyodide/

### ISSUE THREAD

**Issue by peter100u** [berinhard/pyp5js#207]
loading loading "Pyodide is still loading.\nPlease, wait a few seconds and try to run it again."

In addition, I want to run pyodide locally JS is placed in my local P5 HTML. There is no network in the laboratory. We can only run P5 for Python locally

**Comment by berinhard** [comment]
Hi @peter100u,

Pyodide is a big project and it can take a while to be downloaded. The whole pyodide page demo loads 23.37 MB of data and this can lead to an error on slow network connections. I just tested the demo editor and it's working as expected. So maybe you're facing connection issues that are preventing you from using it.

`pyp5js` does have support for offline sketches as well. You can:

1 - Download [the latest zip version](https://github.com/berinhard/pyp5js/archive/refs/heads/develop.zip) of it;
2 - After unzipping it and inside `pyp5js-develop` directory, you can install it with `python setup.py install`
3 - Then, to create sketches which works offline you can use the local web editor. Execute `pyp5js serve` and you should be able to access it on http://127.0.0.1:5000/

The local web editor is completely offline and, thus, should work on your lab.

**Comment by peter100u** [comment]
thank you very much

**Comment by peter100u** [comment]
In that case, I still need to configure a python environment locally, which is not what I want. I just want to run locally, such as on iPad, mobile browser, etc., so I chose https://github.com/skulpt/skulpt
