### ISSUE TITLE
Empty lines are being added.

### ISSUE THREAD

**Issue by imlimws** [berinhard/pyp5js#211]
On the web editor, whenever [save] is clicked, empty lines are added between code lines.
[pyp5js.pptx](https://github.com/berinhard/pyp5js/files/8579735/pyp5js.pptx)
It might not be the problem for every one but for me, this is the only reason I can't work on this lovely pyp5js unfortunately.

**Comment by MrMenezes** [comment]
@imlimws Foi no windowns? Caso sim acho que enviei a correção https://github.com/berinhard/pyp5js/pull/209

**Comment by berinhard** [comment]
Fixed by #209
