### ISSUE TITLE
Show python code in examples page.

### ISSUE THREAD

**Issue by eduardostalinho** [berinhard/pyp5js#22]
I've seen the examples page on github.io and I think we should have the python code on the left side of the sketch result.
We can achieve this by adding an option to transcrypt command like `--render-code` to add the code to the compiled page with p5js running.

What do you think?

**Comment by berinhard** [comment]
I'm :+1:  for this @eduardostalinho. I'm flagging this as an enhancement and as a first thought about how to implement this would be using a different `index.html` file with would have this part with the python code.
