### ISSUE TITLE
collections module is unavailable in Transcrypt

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#26]
I think I'll try this: http://www.collectionsjs.com/deque :)
and https://github.com/aureooms/js-data-structures

**Comment by berinhard** [comment]
@villares this is already under development in transcrypt. More info on [transcrypt's issue #442](https://github.com/QQuick/Transcrypt/issues/442). This is the good news, but the bad one is the last update on this issue was on last year's august =S

**Comment by berinhard** [comment]
I also closed this one because [I documented this limitation]().
