### ISSUE TITLE
Question: should pyp5js CLI accept directory/sketch_name ?

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#27]
I wanted to create a new sketch further down the directory tree...
```
unipath.errors.UnsafePathError: arg '2019/sketch_190508a.py' contains path separator '/'
```
I'm not sure that would be very useful :)

**Comment by berinhard** [comment]
I added this to the initial API but it's bugged =X

Working on this now at [feature/sketch-dir-cli](https://github.com/berinhard/pyp5js/tree/feature/sketch-dir-cli) branch
