### ISSUE TITLE
Something wrong with pop() [WEBGL constant is another issue]

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#3]
I'm sure we'll have 3D at some point :)

So let's put a small test example here:

```
from pyp5js import *

def setup():
    createCanvas(600, 600, WEBGL)
    
def draw():
  background(200)
  translate(-240, -100, 0)
  normalMaterial()
  push()
  rotateZ(frameCount * 0.01)
  rotateX(frameCount * 0.01)
  rotateY(frameCount * 0.01)
  box(50, 70, 100)
  pop()

start_p5(setup, draw)
```

I guess this is a bit early... but, who knows?

**Comment by villares** [comment]
Using _P5_INSTANCE.WEBGL I get this:
`TypeError: _P5_INSTANCE.py_pop is not a function`

**Comment by berinhard** [comment]
I got the same error here, but at least the 3D is working for now WEBGL.

**Comment by berinhard** [comment]
**Updates to ongoing investigation**

**Comment by berinhard** [comment]
Transcrypt's `__pragma__` seemed to deal with the problem. The following snippet in `pyp5js/pytop5js.py` worked for me:

```
def pop(*args):
    __pragma__ ('noalias', 'pop')
    _P5_INSTANCE.pop()
    __pragma__ ('alias', 'pop', 'py_pop')
```

**Comment by eduardostalinho** [comment]
Based on https://www.transcrypt.org/docs/html/special_facilities.html#id2, I think there are more instructions with this issue..

**Comment by berinhard** [comment]
@eduardostalinho I think this is true only for methods from P5.js that matches with any of those aliases definition. I spent today's morning taking a look at them and it seemed that case only occurs with `p5.pop` function.

Anyway, if we have the same error in the future with other functions, we'll already know how to fix them. So, I'm closing this issue as solved! Thanks for your PR =]

**Comment by kylepollina** [comment]
Hi all, I think this issue might have to open up again, or at least as a separate issue. 

[p5.Renderer](https://p5js.org/reference/#/p5.Renderer) objects also contain `pop()` and `clear()` methods that are renamed during the transcrypt stage. For example, a simple Python script like this:

```python
from pyp5js import *

def setup():
    createCanvas(700, 700)

    gr = createGraphics(500, 500)
    gr.push()
    gr.pop()
```
will get compiled into this equivalent Javascript

```javascript
export var setup = function () {
	if (arguments.length) {
		var __ilastarg0__ = arguments.length - 1;
		if (arguments [__ilastarg0__] && arguments [__ilastarg0__].hasOwnProperty ("__kwargtrans__")) {
			var __allkwargs0__ = arguments [__ilastarg0__--];
			for (var __attrib0__ in __allkwargs0__) {
			}
		}
	}
	else {
	}
	createCanvas (700, 700);
	var gr = createGraphics (500, 500);
	gr.push ();
	gr.py_pop ();
};
```

Which will result in the following error `Uncaught TypeError: gr.py_pop is not a function`. The same happens for the following:
```python
gr = createGraphics(500, 500)
gr.clear()
```
gets transcrypted into

```javascript
var gr = createGraphics (500, 500);
gr.push ();
gr.py_clear ();
```
Creates the error `Uncaught TypeError: gr.py_clear is not a function`.

I have tried the following in the `pyp5js.py` file:
```python
def createGraphics(*args):
    __pragma__('noalias', 'pop')
    graphics = _P5_INSTANCE.createGraphics(*args)
    __pragma__('alias', 'pop', 'py_pop')
    return graphics
```
but didn't fix anything. Do any of you have thoughts on how this can be avoided? Or is this purely due to transcrypt?

**Comment by kylepollina** [comment]
Oh you know what, nevermind. I now understand I can do this instead in my python script and it will work as expected:
```python
from pyp5js import *

def setup():
    createCanvas(700, 700)

    gr = createGraphics(500, 500)
    gr.push()
    __pragma__('noalias', 'pop')
    gr.pop()
    __pragma__('alias', 'pop', 'py_pop')
```

The pragma just needs to be in my code instead of in the pyp5js library.

**Comment by berinhard** [comment]
Thanks for figuring this out @kylepollina! Unfortunately pyodide support (#124) is not ready yet. Once we have this done, these transcrypt specific fixes won't be necessary anymore =]
