### ISSUE TITLE
Add link from the live examples to their python code

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#33]
While #22 is not ready, I guess there's a smaller step to improve our examples. We could just add links from the html - after all they can have any html we want - to the related python code in the github repo.

**Comment by villares** [comment]
I like this! Earlier when Processing was used to generate "Java applets", and even when ProcessingJS was a thing, the pages used to have a link to the code and a "made with Processing" tag.

**Comment by berinhard** [comment]
@villares did a very nice job with #40, but I think we can still improve this linking.

We could add something like [the Github ribbons](https://github.blog/2008-12-19-github-ribbons/) with "See sketch code" over the sketch result. This could be placed on the upper right top corner of the window to don't pollute to much the sketch canvas.

The ribbon could redirect the user to the source code from the sketch html. I think this is desirable since I'm [sharing the unique demo links](https://twitter.com/bbfontes/status/1128265675984855040) and not the examples index page.
