### ISSUE TITLE
p5.Vector static methods aren't accessible

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#37]
Rigth now we can't call ['p5.PVector.random2d`](https://p5js.org/reference/#/p5.Vector/random2D), for example. 

@villares I think we could expose a global variable `p5` so this would work exactly as in the docs. What do you think? Right now, the way to use `PVector` is via `_P5_INSTANCE.PVector` but I really don't feel this is ideal =S

**Comment by villares** [comment]
Go for it!

**Comment by berinhard** [comment]
Actually, we already have the global `p5` variable because of the `p5.js` file hehehe. So the code following code already works:

```python
from pytop5js import *


def setup():
    createCanvas(900, 900)
    stroke(27, 27, 27, 5)
    strokeWeight(2)


def draw():
    push()

    translate(width / 2, height / 2)
    v = p5.Vector.random2D()
    v.normalize()
    v.mult(random(100, 400))
    line(0, 0, v.x, v.y)

    pop()


start_p5(setup, draw, {})
```

I'll leave this issue as open so we can add this example to our examples list as a Vector example.

**Comment by berinhard** [comment]
The example is kind of cool to hehehe It look like there's a hole growing on your computer screen!

**Comment by villares** [comment]
Maybe you should close this issue then?

**Comment by berinhard** [comment]
@villares I just have to add this code to our examples list. Once it's done, I'm cool to close it. As soon as my family's vistis season end (by the end of may) I'll get back to `pyp5js`. So far, I'm really busy being a Recife's touristic guide hehe
