### ISSUE TITLE
width & height system variables unavailable inside setup()

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#46]
I believe that most system variables (like `mouseX` and `mouseY`) are assigned to their P5 equivalents in code that runs before `draw()`... this way `width` and `height` have value 100 inside `setup()`.

We need to find a way to update them immediately after `createCanvas()`,

**Comment by berinhard** [comment]
Just to have a reference, the following code should log 300 and 600 in the browser console:

```javascript
function setup() {
	createCanvas(300, 600)
	
	console.log(width)
	console.log(height)
}

function draw() {
	rect(10, 10, 100, 100)
}
```

**Comment by berinhard** [comment]
Just to have a reference, the following p5.js code should work with pyp5js as well. It logs 300 and 600 in the browser console:

```javascript
function setup() {
	createCanvas(300, 600)
	
	console.log(width)
	console.log(height)
}

function draw() {
	rect(10, 10, 100, 100)
}
```
