### ISSUE TITLE
mouseWheel() "event" not available

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#60]
The `mouseWheel` function is executed, but `TypeError: event is undefined`.

```
from pytop5js import *

def setup():
    createCanvas(500, 500)

def draw():
    rect(100, 20, 10, 10)
	# text(str(width), 100, 200)

def mouseWheel(event):
	rect(200, 20, 20, 20)
	text(str(event.delta), 100, 100)

# ==== This is required by pyp5js to work
# Register your events functions here
event_functions = {
   "mouseWheel": mouseWheel
}
start_p5(setup, draw, event_functions)
```

**Comment by berinhard** [comment]
@villares it worked for me after removing the `event` parameter from the `mouseWheel` function definition. Maybe it's something to be documented at https://berinhard.github.io/pyp5js/#known-issues-and-differences-to-the-processingpy-and-p5js-ways-of-doing-things? 

Could you do that? Maybe this same issue is happening with other event functions as well.

**Comment by villares** [comment]
Gosh! JavaScript is just mad. Sure, I'll doc it.
