### ISSUE TITLE
'disallowed MIME type (“text/html”)' error on localhost deployment of sketch

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#69]
I'm not sure this is a pyp5js issue or maybe a http.server issue, and I think someone told me something about it but I can't remember.

The point is when serving on localhost I'm getting this console error and it is a show-stopper for my studies:
```
Loading module from “http://localhost:8000/target/target_sketch.js” was blocked because of a disallowed MIME type (“text/html”).
```

**Comment by villares** [comment]
I have this other sketch givim the same error message  (and this one does not contain loadImage):

https://github.com/villares/sketch-a-day/tree/master/2019/sketch_190630a/s190630web

**Comment by berinhard** [comment]
@villares probably this error is closely related to #72, so I'm clossing this issue
