### ISSUE TITLE
loadImage might be broken

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#70]
This may be the cause of issue #69 

Code example using `loadImage()` at: https://github.com/villares/para_plan
Served at: https://abav.lugaralgum.com/para_plan/

PS: I have tried several ways of referencing the asset...

**Comment by berinhard** [comment]
@villares this issue is now fixed as documented in [example 009](https://berinhard.github.io/pyp5js/examples/sketch_009/index.html).

Please, update your `pyp5js` to version **0.4.2** with:

```
$ pip install --upgrade pyp5js
```
