### ISSUE TITLE
Firefox no longer ignores CORS for file URIs

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#72]
Since [this last update](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default), firefox now is forcing CORS even for local files. Because of that, now we may need an http server to serve the sketch's `index.html`

**Comment by GoToLoop** [comment]
- Alternatively, go to Firefox's <kbd>about:config</kbd>.
- And in the search there paste: <kbd>privacy.file_unique_origin</kbd>.
- Double-click the entry to make its value `false`.

Another option would be to ask the p5js devs to automatically turn off CORS when the scheme is `file://`

**Comment by berinhard** [comment]
Thanks for the comment @GoToLoop! You've saved my life a lot of times with your posts in the processing's forums and I'm very happy to know you're keeping one eye on `pyp5js`.

Thanks for documenting this configuration alternative. It'll be very helpful until we have `pyp5js` properly dealing with that issue.

Turning off the `privacy.file_unique_origin` settings is what I'm doing so far to be able to keep on using the lib locally. But I feel that this extra configuration can be very frustrating or even very difficult for new comers on programming.

I hope I can fix this soon =]

**Comment by GoToLoop** [comment]
> Thanks for documenting this configuration alternative.

Actually the workaround was in the link you had posted:
https://Developer.Mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp#Local_File_Security_in_Firefox_68

**Comment by berinhard** [comment]
### How to fix this issue

My idea is to change the `monitor` to also run a simple HTTP server. For example:

```bash
$ python3 -m http.server 8000 --bind 127.0.0.1 
```

When I run this command from inside a sketch's directory, I can already see the results by accessing `http://localhost:8000/`. But, in my opinion, this command requires extra knowledge beyond `pyp5js`'s API and because of that it's not user-friendly.

So, I'd like to keep the solution but avoiding the headache of more command line stuff. That's why I think the `monitor` command is a good candidate to start this server. The best places to start in the code are:

- Monitor's command [implementation](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/monitor.py);
- Unit [tests](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/tests/test_monitor.py);

Python reference on HTTP servers can be found [here](https://blog.anvileight.com/posts/simple-python-http-server/) and [here](https://code-maven.com/static-server-in-python).

**Comment by turicas** [comment]
We could use gunicorn (importing from Python as a library), like in: http://docs.gunicorn.org/en/stable/custom.html
