### ISSUE TITLE
Use Jinja2's template inheritance for the web app templates

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#79]
Currtenly, [all the templates](https://github.com/berinhard/pyp5js/tree/develop/pyp5js/http/templates) used by de dev server are hardcoded beause a `base.html` doesn't exist. 

The goal of this ticket is to refactor them to [extend from a base template](https://jinja.palletsprojects.com/en/2.10.x/templates/#base-template).

**Comment by jodli** [comment]
I would like to try this now! :)

**Comment by berinhard** [comment]
Fixed by #85
