### ISSUE TITLE
Add a minimal CSS structure to the web server app

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#80]
Maybe it would be better to work on this issue after #79  is done because both of them have a similar goal: to improve the web interface. I don't want to add flashing buttons, colors or very complicated stuff 'cause I'm a fan of the [brutalist or minmalist web](https://brutalistwebsites.com/). My main goals here are:

- Use [basscss](https://basscss.com/) to organize the content disposion;
- A less raw HTML implementation for the [new_sketch_form.html](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/http/templates/new_sketch_form.html);

**Comment by mosesmeirelles** [comment]
I would be happy to take this up @berinhard

**Comment by berinhard** [comment]
Assigned @mosesmeirelles! Are we going to meet each other at PythonBrasil this year? I hope so!!!

**Comment by mosesmeirelles** [comment]
Sure @berinhard I'll be there on days 25, 26 :smile:
