### ISSUE TITLE
Unit test the http.web_app code

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#81]
The web application doesn't have a single test and this is not ideal hehe. The tests scenarios for each one of the routes are listed bellow. [This series](https://damyanon.net/post/flask-series-testing/) can work as a quick reference on how to test Flask application.

### Route /
- Ensure the sketches are being listed with valid links

### Route /new-sketch/
- On GET should render the new sketch form;
- POST without `sketch_name` should render the form again with an error message;
- POST with an existing `sketch_name` should render the form again with an error message;
- POST with a valid `sketch_name` should create the new sketch directory and files and render success page

### Route /sketch/<sketch_name>
- 404 if sketch does not exist
- Should return the sketch's `index.html` if it exists
- Should add the sketch's static files when the route has an additional path, such as `/sketch/foo/static/style.css`
- Set `Content-Type=application/javascript` header for the javascript files;
- 404 if the static file does not exist

**Comment by isabarros** [comment]
Can take a look on that @berinhard !

**Comment by berinhard** [comment]
Sure @isabarros! I've assigned this to you =]

**Comment by berinhard** [comment]
Fixed by #93
