### ISSUE TITLE
Run integration tests in Circle.ci

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#83]
Currenty we're only using Circle.CI to run the tests (#67). It would be nice to also test the build process. My rough notion of steps to do so are:

- create a venv;
- really install pyp5js in the venv (`python setup.py install`);
- run `pyp5js new foo`;
- run `pyp5js transcrypt foo`;
- make sure all the files were created as expected;

For the last step, maybe we could add a script in the `utils` to, given a directory, it checks if all the files required by pyp5js are there.

**Comment by Olyno** [comment]
Hi, can you assign me this issue please?

**Comment by turicas** [comment]
The following steps may be created as automated tests using [click's test API](http://click.palletsprojects.com/en/5.x/testing/):

- run pyp5js new foo;
- run pyp5js transcrypt foo;
- make sure all the files were created as expected;

So CircleCI execution could be limited to: 

- Create venv
- Install pyp5js using code from repository
- Execute the test runner

**Comment by berinhard** [comment]
Wow I didn't know this click's test API. Thanks for the link @turicas.

@Olyno I've assigned this PR to you :+1:

**Comment by Olyno** [comment]
> The following steps may be created as automated tests using click's test API

Did you make these changes before? I mean, the current code already contains these changes or not yet? @berinhard

**Comment by berinhard** [comment]
@Olyno yep, the code already exposes this API. It's just a matter of configuring circle-ci to have this additional step on validating this API.

Currently the circle.ci only runs the unit tests, but we'd like to have a more user experience integration tests also. That's why we'd have to run the commands from the command line.

**Comment by berinhard** [comment]
Marking this issue as done since now we have our [build process](https://github.com/berinhard/pyp5js/actions) on Github under Linux, Windows and MacOs.
