### ISSUE TITLE
Sketch names must always start with letters

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#84]
Because the sketch name is used [in an import statement](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/templates/target_sketch.py.template#L1), they must always start with letters and must only have alphanumeric chars. 

The [`SketchFiles.__init__`](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/fs.py#L10) method should perform this check and raise a custom exception if it fails.

**Comment by isabarros** [comment]
Can add that :)

**Comment by isabarros** [comment]
Please check: https://github.com/berinhard/pyp5js/pull/86

**Comment by berinhard** [comment]
Fixed by #86
