### ISSUE TITLE
Keep Python functions with name conflict with p5.js working as expected

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#90]
There are 3 name conflicts between p5.js and Python for the following functions:

- `map`: [p5.js reference](https://p5js.org/reference/#/p5/map) VS [Python reference](https://docs.python.org/3.5/library/functions.html#map);
- `filter`: [p5.js reference](https://p5js.org/reference/#/p5/filter) VS [Python reference](https://docs.python.org/3.5/library/functions.html#filter);
- `set`: [p5.js reference](https://p5js.org/reference/#/p5/filter) VS [Python reference](https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset);

Py.processing has the same problem and it's documented under the section [Conflicting names](https://py.processing.org/tutorials/python-jython-java/) in the docs.

With pyp5js we could run some checks on the `args` for these functions, instead of the [current direct dispatch](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/pyp5js.py#L664) to p5.js. With the checks, we could determine if we want to call the Python function or the p5.js one.

**Comment by isabarros** [comment]
@berinhard I can give that a try

**Comment by berinhard** [comment]
@isabarros go, go, go!
