### ISSUE TITLE
Issue creating sketch with empty name

### ISSUE THREAD

**Issue by mosesmeirelles** [berinhard/pyp5js#97]
Testing new sketch screen, found what I think to be an issue trying to create a sketch with empty name. Trying empty name results showing an error of `"<sketch_dir> already exists"`, tested on Ubuntu 18 and Windows 8 and got same scenario:

![Selection_062](https://user-images.githubusercontent.com/6470574/67166787-158a1f80-f369-11e9-9e1a-ba2dd02ee945.png)

when what I think it's expected is the empty message on: https://github.com/berinhard/pyp5js/blob/1cae2b3e016ba2854fa29d0a360b9bf510bdfcb4/pyp5js/http/web_app.py#L37

**Comment by isabarros** [comment]
@mosesmeirelles I think this is going to be fixed by https://github.com/berinhard/pyp5js/pull/93
@berinhard please check

**Comment by mosesmeirelles** [comment]
Yes, I think so. That's nice, thanks @isabarros . I'll Just wait for @berinhard confirmation, so I can close this issue.

**Comment by berinhard** [comment]
Precisely as @isabarros said. Fixed by #93
