### ISSUE TITLE
Add sketch code to rendered page (read-only)

### ISSUE THREAD

**Issue by turicas** [berinhard/pyp5js#99]
Such as [the examples on docs](https://berinhard.github.io/pyp5js/examples/sketch_001/index.html).

**Comment by berinhard** [comment]
This should be done the web app when rendering the template. So, instead of just returning the sketch's `index.html` file, it should render a base template with the Python code in the context.

Info here https://github.com/berinhard/pyp5js/blob/develop/pyp5js/http/web_app.py#L55
